(git) Update git-based Ctags generation
Running this caused a buildup of orphaned Neovim processes that would
drain resources (e.g., battery). Lazy.nvim generates help tags so the
manual step may not be needed.

This also skips generating Ctags in the home directory. Not sure when
they'd be needed.

diff --git a/.config/git/hooks/ctags b/.config/git/hooks/ctags
--- a/.config/git/hooks/ctags
+++ b/.config/git/hooks/ctags
@@ -2,21 +2,12 @@
 
 set -e
 
-if [ -d doc -a \( -d autoload -o -d ftdetect -o -d plugin \) ]; then
-  nohup nvim -u NONE -c 'helptags doc' -cq >/dev/null 2>&1 </dev/null &
+if [ "$PWD" = "$HOME" ]; then
+  echo "Script cannot be run from the home directory."
+  exit 1
 fi
 
-optfiles=`git ls-files -oc --directory -- .ctags '*/.ctags'`
-
-IFS='
-'
-for optfile in ${optfiles:-./fake}; do
-  (
-  unset GIT_DIR GIT_WORK_TREE
-  tmpfile=`mktemp ${TMPDIR:-/tmp}/tags.XXXXXXXXXX~`
-  cd `dirname $optfile`
-  trap 'rm -f $tmpfile' EXIT INT TERM
-  git ls-files | ctags -L - -f $tmpfile "$@"
-  mv $tmpfile tags
-  )
-done
+dir="`git rev-parse --git-dir`"
+trap 'rm -f "$dir/tags.$$"' EXIT INT TERM
+git ls-files | ctags --tag-relative -L - -f$dir/tags.$$ --languages=-javascript,sql
+mv $dir/tags.$$ $dir/tags
